name: auth
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  particle_auth: ^0.13.0
  ethers: 
    git: https://github.com/tarunmahe/ethers
  web3dart: ^2.6.1
  http: ^0.13.6
  particle_connect: ^0.13.5
  walletconnect_dart: ^0.0.11
  url_launcher: ^6.1.11
  flutter_svg: ^2.0.6
  fluttertoast: ^8.2.2
  flutter_screenutil: ^5.8.4
  particle_wallet: ^0.13.5
  particle_biconomy: 
    path: ../
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.0


flutter:
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Erica One
      fonts:
        - asset: assets/fonts/EricaOne-Regular.ttf
          style: normal
          weight: 400
    - family: Aunchanted Xspace
      fonts:
        - asset: assets/fonts/Aunchantedxspace-ogg4.ttf
          weight: 400
          style: normal
    - family: Solomon's Key True Type
      fonts: 
        - asset: assets/fonts/SolomonsKeyTrueType-EXOW.ttf
          weight: 400
 
        


  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
